### PR TITLE
Make runnable example blocks

### PR DESCRIPTION
**Pull request by avik-pal**

### CODE REVIEW

**Comment by avik-pal** [comment]
@ChrisRackauckas  did the examples actually run? I don't see the outputs https://sciml.github.io/DeepEquilibriumNetworks.jl/previews/PR72/manual/deqs/#DeepEquilibriumNetworks.DeepEquilibriumNetwork

**Comment by ChrisRackauckas** [comment]
Oops, didn't see they were in docstrings 😓

**Comment by avik-pal** [comment]
Never tried it before do `@example` blocks not run in docstrings? I can put down a tutorial over the weekend

**Comment by ChrisRackauckas** [comment]
Yeah I guess not.

**Pull request merged**
