### PR TITLE
Better Steady State Adjoint

### PR DESCRIPTION
**Pull request by avik-pal**
Sister PR to https://github.com/SciML/SciMLSensitivity.jl/pull/877

~- [ ] Compare the improved SSAdjoint Methods~

## Fast DEQ Solves using JNFK

```julia

using DeepEquilibriumNetworks, LuxAMDGPU, Lux, Random, OrdinaryDiffEq, Zygote,
    SciMLSensitivity, LinearAlgebra, NonlinearSolve, LegibleLambdas, Statistics, Optimisers,
    LinearSolve

import Lux.Experimental: @compact

function NonlinearSolve.SparseDiffTools.get_tag(::AbstractArray{
    NonlinearSolve.ForwardDiff.Dual{T, V, N}}) where {T, V, N}
    return T
end

dudt = @compact(; c1=CrossCor((3, 3), 1 => 4, swish; pad=SamePad()),
    c2=CrossCor((3, 3), 1 => 4, swish; pad=SamePad()),
    c3=Chain(;
        l1=CrossCor((3, 3), 8 => 32, swish; pad=SamePad()),
        l2=CrossCor((3, 3), 32 => 128, swish; pad=SamePad()),
        l3=CrossCor((3, 3), 128 => 32, swish; pad=SamePad()),
        l4=CrossCor((3, 3), 32 => 8, swish; pad=SamePad()),
        l5=CrossCor((3, 3), 8 => 1; pad=SamePad()))) do (u, x)
    return c3(cat(c1(u), c2(x); dims=Val(3)))
end

dev = gpu_device()

model = DeepEquilibriumNetwork(dudt,
    DiscreteDEQSolver(NewtonRaphson(; linsolve=SimpleGMRES()));
    abstol=1.0f-6, reltol=1.0f-6, maxiters=20)

x = randn(Float32, 32, 32, 1, 16) |> dev;

ps, st = Lux.setup(Xoshiro(0), model) |> dev;

model(x, ps, st)
```

### CODE REVIEW

**Comment by avik-pal** [comment]
With https://github.com/SciML/SciMLSensitivity.jl/pull/918 this should be done

**Comment by ChrisRackauckas** [comment]
Why is a special adjoint still needed?

**Comment by avik-pal** [comment]
There is no special adjoint. I just migrated to using the non-component arrays version

**Comment by avik-pal** [comment]
The name is from the SciMLSensitivity change :sweat_smile:

**Comment by avik-pal** [comment]
Needs to wait till https://github.com/LuxDL/Lux.jl/pull/425 is merged

**Pull request merged**
