### PR TITLE
[WIP] Make FastDEQs fast again

### LINKED ISSUE #37: Different ODE Solvers
Test `VCABM` instead of `Tsit5` for continuous DEQ.

### PR DESCRIPTION
**Pull request by avik-pal**
## Main Changes:

* Moves from Flux to [Lux](https://github.com/avik-pal/Lux.jl) -- Mainly to do away with the weird destructure/restructure and the several issues that come with it
* Drop dependencies on unreleased branches (still requires some upstream merges but after this PR we can finally register the package)
* Termination and Time-Stepping Tolerances have separate arguments

## TODOs

- [x] Work on the Discrete Solvers
- [ ] Jacobian Stabilization is completely broken
- [ ] Update docs

Fixes #37 

Requires https://github.com/avik-pal/ExplicitFluxLayers.jl/pull/7 & https://github.com/avik-pal/FluxMPI.jl/pull/15

### CODE REVIEW

**Comment by avik-pal** [comment]
Some numbers after this partial rewrite -- CIFAR10 now takes 320s per epoch on 1 V100 vs previously 450s on 6 processes across 2 V100s

**Comment by avik-pal** [comment]
Ok, we are definitely not fast yet. `deq` uses discrete models but is able to train 1 epoch in 10s.

**Comment by ChrisRackauckas** [comment]
Where's the overhead right now? Do you have a profile?

**Comment by avik-pal** [comment]
I am working on it. There was some overhead in EFL due to branching, which Zygote doesn't like. Fixing that brings us at par with Pytorch on standard workloads like AlexNet.

**Comment by ChrisRackauckas** [comment]
I'd be curious to see a flamegraph to just know "how it flows" and know what can be done.

**Comment by ToucheSir** [comment]
FYI https://github.com/FluxML/Zygote.jl/pull/1195 would make branching less terrible for performance, but the backwards pass will still be type unstable.

**Comment by avik-pal** [comment]
> I'd assume most of the time would be in implicit adjoints, so I'd assume Zygote overhead would be negligible here. But if that's not the case, I'm curious why.

Not really even when running `pretraining` which is essentially ignore adjoints and train like a depth K neural network we have a large overhead. But yeah I will get the flame graphs before concluding things

**Comment by avik-pal** [comment]
Some profiles. Not for the actual models but smaller ones atm

# Script: small.jl

```julia
using FastDEQ, CUDA, LinearAlgebra, Random, Test, ExplicitFluxLayers, Flux, ProfileView, BenchmarkTools

seed = 0
rng = Random.default_rng()
Random.seed!(rng, seed)

model = DEQChain(
    EFL.Dense(2, 2),
    DeepEquilibriumNetwork(
        EFL.Parallel(+, EFL.Dense(2, 2; bias=false), EFL.Dense(2, 2; bias=false)),
        ContinuousDEQSolver(; abstol=0.1f0, reltol=0.1f0, abstol_termination=0.1f0,
                            reltol_termination=0.1f0, mode=:rel_norm),
        maxiters=10,
        verbose=false
    ),
)
ps, st = gpu.(EFL.setup(rng, model))
x = gpu(rand(rng, Float32, 2, 1))
y = gpu(rand(rng, Float32, 2, 1))

gs = gradient(p -> sum(abs2, model(x, p, st)[1][1] .- y), ps)

@profview for i in 1:10
    sum(abs2, model(x, ps, st)[1][1] .- y)
    CUDA.synchronize()
end

@profview for i in 1:10
    gradient(p -> sum(abs2, model(x, p, st)[1][1] .- y), ps)
    CUDA.synchronize()
end
```

# Script 2: small_wide.jl

```julia
using FastDEQ, CUDA, LinearAlgebra, Random, Test, ExplicitFluxLayers, Flux, ProfileView, BenchmarkTools

seed = 0
rng = Random.default_rng()
Random.seed!(rng, seed)

model = DEQChain(
    EFL.Dense(2, 1024),
    DeepEquilibriumNetwork(
        EFL.Parallel(+, EFL.Dense(1024, 1024; bias=false), EFL.Dense(1024, 1024; bias=false)),
        ContinuousDEQSolver(; abstol=0.1f0, reltol=0.1f0, abstol_termination=0.1f0,
                            reltol_termination=0.1f0, mode=:rel_norm),
        maxiters=10,
        verbose=false
    ),
    EFL.Dense(1024, 2),
)
ps, st = gpu.(EFL.setup(rng, model))
x = gpu(rand(rng, Float32, 2, 16))
y = gpu(rand(rng, Float32, 2, 16))

gs = gradient(p -> sum(abs2, model(x, p, st)[1][1] .- y), ps)

@profview for i in 1:10
    sum(abs2, model(x, ps, st)[1][1] .- y)
    CUDA.synchronize()
end

@profview for i in 1:10
    gradient(p -> sum(abs2, model(x, p, st)[1][1] .- y), ps)
    CUDA.synchronize()
end
```

[small_wide_1.txt](https://github.com/SciML/FastDEQ.jl/files/8544041/small_wide_1.txt)
[small_wide_2.txt](https://github.com/SciML/FastDEQ.jl/files/8544042/small_wide_2.txt)
[small_2.txt](https://github.com/SciML/FastDEQ.jl/files/8544043/small_2.txt)
[small_1.txt](https://github.com/SciML/FastDEQ.jl/files/8544044/small_1.txt)

The files are *.jlprof and not *.txt

**Comment by avik-pal** [comment]
The NeuralNetwork evaluation takes up very little time of the forward pass (red part)
image

**Comment by avik-pal** [comment]
```julia
julia> @benchmark model(x, ps, st)[1][2]
BenchmarkTools.Trial: 513 samples with 1 evaluation.
 Range (min … max):  6.803 ms … 393.693 ms  ┊ GC (min … max): 0.00% … 10.86%
 Time  (median):     7.153 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   9.734 ms ±  29.416 ms  ┊ GC (mean ± σ):  2.54% ±  0.82%

   ▁▆█▄▄                                                       
  ▃██████▇▇▄▄▃▃▃▃▃▃▃▂▃▃▂▃▂▁▃▂▃▄▂▅▃▄▃▃▂▃▂▂▁▁▁▂▂▁▂▂▂▂▁▁▁▂▁▁▁▁▁▂ ▃
  6.8 ms          Histogram: frequency by time        10.5 ms <

 Memory estimate: 643.28 KiB, allocs estimate: 10811.

julia> @benchmark model(x, ps, st_)[1][2]
BenchmarkTools.Trial: 1333 samples with 1 evaluation.
 Range (min … max):  1.319 ms … 386.675 ms  ┊ GC (min … max): 0.00% … 7.30%
 Time  (median):     3.094 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.743 ms ±  14.787 ms  ┊ GC (mean ± σ):  1.27% ± 0.32%

                                  ▇█▂         ▂▂▁▁             
  █▇▇▅▃▅▁▁▁▁▁▁▃▁▁▃▁▁▃▁▁▁▃▃▁▁▁▁▁▁▁▇███▅▄▅▄▃▇▄▄█████▆▁▁▁▃▁▁▃▆▇▇ █
  1.32 ms      Histogram: log(frequency) by time      4.46 ms <

 Memory estimate: 91.98 KiB, allocs estimate: 2386.
```

The second run is essentially the time it takes if we remove adaptive timestepping and execute the neural networks K times (K = NFE for first run)

**Comment by ChrisRackauckas** [comment]
https://github.com/tkluck/StatProfilerHTML.jl

**Comment by avik-pal** [comment]
https://avik-pal.github.io/statprofs/1/
https://avik-pal.github.io/statprofs/2/

**Comment by ChrisRackauckas** [comment]
How far off is the performance now? Check if the Krylov method is actually a good idea for the linear solve of the backwards pass. For a dense matrix it can have really slow convergence. A direct solve may be better there at the size you're using?

**Comment by avik-pal** [comment]
Actually https://avik-pal.github.io/statprofs/3/index.html is a much more realistic test case. Most of the time ~85% is spent in the neural network evaluation

**Comment by avik-pal** [comment]
Progress we are down from 180s per epoch across 4 gpus to 115s per epoch across 1 GPU

**Pull request merged**
